### ISSUE TITLE
Sequenciador

### ISSUE THREAD

**Issue by mateusmaiamaia** [fga-eps-mds/2024.2-LIVRO-LIVRE-DOC#17]
“Esta funcionalidade é importante?”. Sempre obtive a mesma resposta quando fiz tal pergunta. Por isso, não a faço mais. A pergunta mais relevante para ajudá-lo a planejar a ordem das funcionalidades a serem criadas é: “Qual
dessas duas é mais prioritária?”.
Isso fará com que as funcionalidades sejam priorizadas relativamente umas às outras. Essa pergunta é muito útil e deve ser utilizada, mas precisa de um ponto de partida.
Previamente, você apontou o usuário mais importante, bem como a jornada mais prioritária. Este sim é o melhor ponto de partida: a primeira funcionalidade desta jornada. Talvez mais de uma funcionalidade esteja na jornada, ou em outras jornadas que podem ser criadas ao mesmo tempo. Daí sim, em tal cenário, você deve perguntar qual das duas funcionalidades em questão é a mais prioritária.
Felizmente, nas etapas anteriores alguns parâmetros já foram adicionados às funcionalidades. São eles: valor de negócio ($, $$ ou $$$), o valor de UX (um, dois ou três corações), o esforço (E, EE ou EEE) e a marcação de nível de confiança (nível alto, médio ou baixo). Esses parâmetros vão ajudar você com o planejamento das funcionalidades e suas prioridades relativas.

## Objetivos
1. Fornecer uma descrição abrangente com exemplos reais para ilustrar cada categoria.
2. Garantir que a documentação seja de fácil entendimento para membros técnicos e não técnicos da equipe.
3. Destacar a importância dessa atividade na definição do escopo do sistema e no gerenciamento de expectativas dos stakeholders.

**Comment by matheusyanmonteiro** [comment]
@mateusmaiamaia  atualize a branch com os novos codigos da main por favor
