### ISSUE TITLE
Plano de custos

### ISSUE THREAD

**Issue by mateusmaiamaia** [fga-eps-mds/2024.2-LIVRO-LIVRE-DOC#23]
Descrição: Desenvolver um plano de custos detalhado para o projeto, com o objetivo de estimar e controlar os recursos financeiros necessários para a execução das atividades, garantindo que o projeto seja concluído dentro do orçamento. O plano de custos deve incluir todas as despesas previstas, como custos com pessoal, ferramentas, infraestrutura, licenças e qualquer outro gasto relacionado ao desenvolvimento e à entrega do produto. A gestão eficaz dos custos é essencial para assegurar que o projeto seja financeiramente viável e que os recursos sejam utilizados de maneira eficiente.

## Objetivos 
* Estimar custos diretos e indiretos: Identificar todas as despesas relacionadas ao projeto, incluindo custos com recursos humanos, tecnologia, materiais, licenças de software, etc.
* Dividir os custos por fase: Alinhar os custos estimados a cada fase do projeto (planejamento, desenvolvimento, testes, entrega).

[Planilha-base](https://docs.google.com/spreadsheets/d/1fworEJTHkBpX7QBpzzg3mM9JbbX5zu-EEAi0Yg4osvw/edit?usp=sharing)

**Comment by matheusyanmonteiro** [comment]
Link para o google planilha: 
https://docs.google.com/spreadsheets/d/1fworEJTHkBpX7QBpzzg3mM9JbbX5zu-EEAi0Yg4osvw/edit?usp=sharing
