### ISSUE TITLE
O produto: É - não é - faz - não faz

### ISSUE THREAD

**Issue by mateusmaiamaia** [fga-eps-mds/2024.2-LIVRO-LIVRE-DOC#8]
# Issue: Explicar o tópico "É/Não É, Faz/Não Faz" no Sistema Lean Inception

## Descrição
Desenvolver uma explicação clara e objetiva para o tópico "É/Não É, Faz/Não Faz" no processo de Lean Inception. Este tópico ajuda a definir os limites e o escopo do sistema, especificando:

* O que o sistema é e não é (identidade e propósito).
* O que o sistema faz e não faz (aspectos funcionais e não funcionais).

O objetivo é alinhar as expectativas da equipe e garantir clareza para todas as partes interessadas.

---

## Objetivos
1. Fornecer uma descrição abrangente com exemplos reais para ilustrar cada categoria.
2. Garantir que a documentação seja de fácil entendimento para membros técnicos e não técnicos da equipe.
3. Destacar a importância dessa atividade na definição do escopo do sistema e no gerenciamento de expectativas dos stakeholders.

**Comment by Joaovitor045** [comment]
# Lean-é-nãoé-faz-não faz
## Criei o arquivo do lean inception e fiz a parte do é não é faz não faz
